/**
 * trieve-server
 * Trieve REST API OpenAPI Documentation
 *
 * OpenAPI spec version: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SlimGroup } from '../models/SlimGroup';
import { HttpFile } from '../http/http';

export class BookmarkGroupResult {
    'chunkUuid': string;
    'slimGroups': Array<SlimGroup>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "chunkUuid",
            "baseName": "chunk_uuid",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "slimGroups",
            "baseName": "slim_groups",
            "type": "Array<SlimGroup>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BookmarkGroupResult.attributeTypeMap;
    }

    public constructor() {
    }
}

