/**
 * trieve-server
 * Trieve REST API OpenAPI Documentation
 *
 * OpenAPI spec version: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ChunkMetadata {
    'chunkHtml'?: string | null;
    'content': string;
    'createdAt': Date;
    'datasetId': string;
    'id': string;
    'link'?: string | null;
    'metadata'?: any | null;
    'qdrantPointId'?: string | null;
    'tagSet'?: string | null;
    'timeStamp'?: Date | null;
    'trackingId'?: string | null;
    'updatedAt': Date;
    'weight': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "chunkHtml",
            "baseName": "chunk_html",
            "type": "string",
            "format": ""
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "datasetId",
            "baseName": "dataset_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "link",
            "baseName": "link",
            "type": "string",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any",
            "format": ""
        },
        {
            "name": "qdrantPointId",
            "baseName": "qdrant_point_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "tagSet",
            "baseName": "tag_set",
            "type": "string",
            "format": ""
        },
        {
            "name": "timeStamp",
            "baseName": "time_stamp",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "trackingId",
            "baseName": "tracking_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "weight",
            "baseName": "weight",
            "type": "number",
            "format": "double"
        }    ];

    static getAttributeTypeMap() {
        return ChunkMetadata.attributeTypeMap;
    }

    public constructor() {
    }
}

