/**
 * trieve-server
 * Trieve REST API OpenAPI Documentation
 *
 * OpenAPI spec version: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ClientDatasetConfiguration {
    'CREATE_CHUNK_FEATURE'?: boolean | null;
    'DATE_RANGE_VALUE'?: string | null;
    'DOCUMENT_UPLOAD_FEATURE'?: boolean | null;
    'FILTER_ITEMS'?: any | null;
    'FRONTMATTER_VALS'?: string | null;
    'IMAGE_RANGE_END_KEY'?: string | null;
    'IMAGE_RANGE_START_KEY'?: string | null;
    'LINES_BEFORE_SHOW_MORE'?: number | null;
    'SEARCH_QUERIES'?: string | null;
    'SUGGESTED_QUERIES'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "CREATE_CHUNK_FEATURE",
            "baseName": "CREATE_CHUNK_FEATURE",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "DATE_RANGE_VALUE",
            "baseName": "DATE_RANGE_VALUE",
            "type": "string",
            "format": ""
        },
        {
            "name": "DOCUMENT_UPLOAD_FEATURE",
            "baseName": "DOCUMENT_UPLOAD_FEATURE",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "FILTER_ITEMS",
            "baseName": "FILTER_ITEMS",
            "type": "any",
            "format": ""
        },
        {
            "name": "FRONTMATTER_VALS",
            "baseName": "FRONTMATTER_VALS",
            "type": "string",
            "format": ""
        },
        {
            "name": "IMAGE_RANGE_END_KEY",
            "baseName": "IMAGE_RANGE_END_KEY",
            "type": "string",
            "format": ""
        },
        {
            "name": "IMAGE_RANGE_START_KEY",
            "baseName": "IMAGE_RANGE_START_KEY",
            "type": "string",
            "format": ""
        },
        {
            "name": "LINES_BEFORE_SHOW_MORE",
            "baseName": "LINES_BEFORE_SHOW_MORE",
            "type": "number",
            "format": ""
        },
        {
            "name": "SEARCH_QUERIES",
            "baseName": "SEARCH_QUERIES",
            "type": "string",
            "format": ""
        },
        {
            "name": "SUGGESTED_QUERIES",
            "baseName": "SUGGESTED_QUERIES",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ClientDatasetConfiguration.attributeTypeMap;
    }

    public constructor() {
    }
}

