/**
 * trieve-server
 * Trieve REST API OpenAPI Documentation
 *
 * OpenAPI spec version: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreateChunkData {
    /**
    * HTML content of the chunk. This can also be plaintext. The innerText of the HTML will be used to create the embedding vector. The point of using HTML is for convienience, as some users have applications where users submit HTML content.
    */
    'chunkHtml'?: string | null;
    /**
    * Chunk_vector is a vector of floats which can be used instead of generating a new embedding. This is useful for when you are using a pre-embedded dataset. If this is not provided, the innerText of the chunk_html will be used to create the embedding.
    */
    'chunkVector'?: Array<number> | null;
    /**
    * File_uuid is the uuid of the file that the chunk is associated with. This is used to associate chunks with files. This is useful for when you want to delete a file and all of its associated chunks.
    */
    'fileUuid'?: string | null;
    /**
    * Group is the id of the group that the chunk should be placed into. This is useful for when you want to create a chunk and add it to a group in one request.
    */
    'groupId'?: string | null;
    /**
    * Link to the chunk. This can also be any string. Frequently, this is a link to the source of the chunk. The link value will not affect the embedding creation.
    */
    'link'?: string | null;
    /**
    * Metadata is a JSON object which can be used to filter chunks. This is useful for when you want to filter chunks by arbitrary metadata. Unlike with tag filtering, there is a performance hit for filtering on metadata.
    */
    'metadata'?: any | null;
    /**
    * Tag set is a comma separated list of tags. This can be used to filter chunks by tag. Unlike with metadata filtering, HNSW indices will exist for each tag such that there is not a performance hit for filtering on them.
    */
    'tagSet'?: string | null;
    /**
    * Time_stamp should be an ISO 8601 combined date and time without timezone. It is used for time window filtering and recency-biasing search results.
    */
    'timeStamp'?: string | null;
    /**
    * Tracking_id is a string which can be used to identify a chunk. This is useful for when you are coordinating with an external system and want to use the tracking_id to identify the chunk.
    */
    'trackingId'?: string | null;
    /**
    * Weight is a float which can be used to bias search results. This is useful for when you want to bias search results for a chunk. The magnitude only matters relative to other chunks in the chunk\'s dataset dataset.
    */
    'weight'?: number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "chunkHtml",
            "baseName": "chunk_html",
            "type": "string",
            "format": ""
        },
        {
            "name": "chunkVector",
            "baseName": "chunk_vector",
            "type": "Array<number>",
            "format": "float"
        },
        {
            "name": "fileUuid",
            "baseName": "file_uuid",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "groupId",
            "baseName": "group_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "link",
            "baseName": "link",
            "type": "string",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any",
            "format": ""
        },
        {
            "name": "tagSet",
            "baseName": "tag_set",
            "type": "string",
            "format": ""
        },
        {
            "name": "timeStamp",
            "baseName": "time_stamp",
            "type": "string",
            "format": ""
        },
        {
            "name": "trackingId",
            "baseName": "tracking_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "weight",
            "baseName": "weight",
            "type": "number",
            "format": "double"
        }    ];

    static getAttributeTypeMap() {
        return CreateChunkData.attributeTypeMap;
    }

    public constructor() {
    }
}

