/**
 * trieve-server
 * Trieve REST API OpenAPI Documentation
 *
 * OpenAPI spec version: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreateDatasetRequest {
    /**
    * Client configuration for the dataset, can be arbitrary JSON. We recommend setting to `{}` to start. See docs.trieve.ai for more information or adjust with the admin dashboard.
    */
    'clientConfiguration': any | null;
    /**
    * Name of the dataset. Must be unique within the organization.
    */
    'datasetName': string;
    /**
    * Organization ID that the dataset will belong to.
    */
    'organizationId': string;
    /**
    * Server configuration for the dataset, can be arbitrary JSON. We recommend setting to `{}` to start. See docs.trieve.ai for more information or adjust with the admin dashboard.
    */
    'serverConfiguration': any | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "clientConfiguration",
            "baseName": "client_configuration",
            "type": "any",
            "format": ""
        },
        {
            "name": "datasetName",
            "baseName": "dataset_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "organizationId",
            "baseName": "organization_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "serverConfiguration",
            "baseName": "server_configuration",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateDatasetRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

