/**
 * trieve-server
 * Trieve REST API OpenAPI Documentation
 *
 * OpenAPI spec version: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DatasetDTO } from '../models/DatasetDTO';
import { DatasetUsageCount } from '../models/DatasetUsageCount';
import { HttpFile } from '../http/http';

export class DatasetAndUsage {
    'dataset': DatasetDTO;
    'datasetUsage': DatasetUsageCount;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dataset",
            "baseName": "dataset",
            "type": "DatasetDTO",
            "format": ""
        },
        {
            "name": "datasetUsage",
            "baseName": "dataset_usage",
            "type": "DatasetUsageCount",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DatasetAndUsage.attributeTypeMap;
    }

    public constructor() {
    }
}

