/**
 * trieve-server
 * Trieve REST API OpenAPI Documentation
 *
 * OpenAPI spec version: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Events } from '../models/Events';
import { HttpFile } from '../http/http';

export class EventReturn {
    'event': Array<Events>;
    'fullCount': number;
    'totalPages': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "event",
            "baseName": "event",
            "type": "Array<Events>",
            "format": ""
        },
        {
            "name": "fullCount",
            "baseName": "full_count",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "totalPages",
            "baseName": "total_pages",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return EventReturn.attributeTypeMap;
    }

    public constructor() {
    }
}

