/**
 * trieve-server
 * Trieve REST API OpenAPI Documentation
 *
 * OpenAPI spec version: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ChatMessageProxy } from '../models/ChatMessageProxy';
import { HttpFile } from '../http/http';

export class GenerateChunksRequest {
    /**
    * The ids of the chunks to be retrieved and injected into the context window for RAG.
    */
    'chunkIds': Array<string>;
    /**
    * The model to use for the chat. This can be any model from the openrouter model list. If no model is provided, gryphe/mythomax-l2-13b will be used.
    */
    'model'?: string | null;
    /**
    * The previous messages to be placed into the chat history. The last message in this array will be the prompt for the model to inference on. The length of this array must be at least 1.
    */
    'prevMessages': Array<ChatMessageProxy>;
    /**
    * Prompt for the last message in the prev_messages array. This will be used to generate the next message in the chat. The default is \'Respond to the instruction and include the doc numbers that you used in square brackets at the end of the sentences that you used the docs for:\'. You can also specify an empty string to leave the final message alone such that your user\'s final message can be used as the prompt. See docs.trieve.ai or contact us for more information.
    */
    'prompt'?: string | null;
    /**
    * Whether or not to stream the response. If this is set to true or not included, the response will be a stream. If this is set to false, the response will be a normal JSON response. Default is true.
    */
    'streamResponse'?: boolean | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "chunkIds",
            "baseName": "chunk_ids",
            "type": "Array<string>",
            "format": "uuid"
        },
        {
            "name": "model",
            "baseName": "model",
            "type": "string",
            "format": ""
        },
        {
            "name": "prevMessages",
            "baseName": "prev_messages",
            "type": "Array<ChatMessageProxy>",
            "format": ""
        },
        {
            "name": "prompt",
            "baseName": "prompt",
            "type": "string",
            "format": ""
        },
        {
            "name": "streamResponse",
            "baseName": "stream_response",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GenerateChunksRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

