/**
 * trieve-server
 * Trieve REST API OpenAPI Documentation
 *
 * OpenAPI spec version: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class OrganizationUsageCount {
    'datasetCount': number;
    'fileStorage': number;
    'id': string;
    'messageCount': number;
    'orgId': string;
    'userCount': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "datasetCount",
            "baseName": "dataset_count",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "fileStorage",
            "baseName": "file_storage",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "messageCount",
            "baseName": "message_count",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "orgId",
            "baseName": "org_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "userCount",
            "baseName": "user_count",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return OrganizationUsageCount.attributeTypeMap;
    }

    public constructor() {
    }
}

