/**
 * trieve-server
 * Trieve REST API OpenAPI Documentation
 *
 * OpenAPI spec version: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StripePlan } from '../models/StripePlan';
import { StripeSubscription } from '../models/StripeSubscription';
import { HttpFile } from '../http/http';

export class OrganizationWithSubAndPlan {
    'createdAt': Date;
    'id': string;
    'name': string;
    'plan'?: StripePlan | null;
    'registerable'?: boolean | null;
    'subscription'?: StripeSubscription | null;
    'updatedAt': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "plan",
            "baseName": "plan",
            "type": "StripePlan",
            "format": ""
        },
        {
            "name": "registerable",
            "baseName": "registerable",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "subscription",
            "baseName": "subscription",
            "type": "StripeSubscription",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return OrganizationWithSubAndPlan.attributeTypeMap;
    }

    public constructor() {
    }
}

