/**
 * trieve-server
 * Trieve REST API OpenAPI Documentation
 *
 * OpenAPI spec version: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ChunkMetadata } from '../models/ChunkMetadata';
import { HttpFile } from '../http/http';

export class ReturnCreatedChunk {
    'chunkMetadata': ChunkMetadata;
    'posInQueue': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "chunkMetadata",
            "baseName": "chunk_metadata",
            "type": "ChunkMetadata",
            "format": ""
        },
        {
            "name": "posInQueue",
            "baseName": "pos_in_queue",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return ReturnCreatedChunk.attributeTypeMap;
    }

    public constructor() {
    }
}

