/**
 * trieve-server
 * Trieve REST API OpenAPI Documentation
 *
 * OpenAPI spec version: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ChunkMetadataWithFileData } from '../models/ChunkMetadataWithFileData';
import { HttpFile } from '../http/http';

export class ScoreChunkDTO {
    'metadata': Array<ChunkMetadataWithFileData>;
    'score': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "Array<ChunkMetadataWithFileData>",
            "format": ""
        },
        {
            "name": "score",
            "baseName": "score",
            "type": "number",
            "format": "double"
        }    ];

    static getAttributeTypeMap() {
        return ScoreChunkDTO.attributeTypeMap;
    }

    public constructor() {
    }
}

