/**
 * trieve-server
 * Trieve REST API OpenAPI Documentation
 *
 * OpenAPI spec version: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ScoreChunkDTO } from '../models/ScoreChunkDTO';
import { HttpFile } from '../http/http';

export class SearchChunkQueryResponseBody {
    'scoreChunks': Array<ScoreChunkDTO>;
    'totalChunkPages': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "scoreChunks",
            "baseName": "score_chunks",
            "type": "Array<ScoreChunkDTO>",
            "format": ""
        },
        {
            "name": "totalChunkPages",
            "baseName": "total_chunk_pages",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return SearchChunkQueryResponseBody.attributeTypeMap;
    }

    public constructor() {
    }
}

