/**
 * trieve-server
 * Trieve REST API OpenAPI Documentation
 *
 * OpenAPI spec version: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SetUserApiKeyRequest {
    /**
    * The name which will be assigned to the new api key.
    */
    'name': string;
    /**
    * The role which will be assigned to the new api key. Either 0 (read), 1 (read and write). If not provided, the user role will be used. The auth\'ed user must have a role greater than or equal to the role being assigned.
    */
    'role'?: number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return SetUserApiKeyRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

