/**
 * trieve-server
 * Trieve REST API OpenAPI Documentation
 *
 * OpenAPI spec version: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Organization } from '../models/Organization';
import { UserOrganization } from '../models/UserOrganization';
import { HttpFile } from '../http/http';

export class SlimUser {
    'email': string;
    'id': string;
    'name'?: string | null;
    'orgs': Array<Organization>;
    'userOrgs': Array<UserOrganization>;
    'username'?: string | null;
    'visibleEmail': boolean;
    'website'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "orgs",
            "baseName": "orgs",
            "type": "Array<Organization>",
            "format": ""
        },
        {
            "name": "userOrgs",
            "baseName": "user_orgs",
            "type": "Array<UserOrganization>",
            "format": ""
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string",
            "format": ""
        },
        {
            "name": "visibleEmail",
            "baseName": "visible_email",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "website",
            "baseName": "website",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SlimUser.attributeTypeMap;
    }

    public constructor() {
    }
}

