/**
 * trieve-server
 * Trieve REST API OpenAPI Documentation
 *
 * OpenAPI spec version: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class StripePlan {
    'amount': number;
    'chunkCount': number;
    'createdAt': Date;
    'datasetCount': number;
    'fileStorage': number;
    'id': string;
    'messageCount': number;
    'name': string;
    'stripeId': string;
    'updatedAt': Date;
    'userCount': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "chunkCount",
            "baseName": "chunk_count",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "datasetCount",
            "baseName": "dataset_count",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "fileStorage",
            "baseName": "file_storage",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "messageCount",
            "baseName": "message_count",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "stripeId",
            "baseName": "stripe_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "userCount",
            "baseName": "user_count",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return StripePlan.attributeTypeMap;
    }

    public constructor() {
    }
}

