/**
 * trieve-server
 * Trieve REST API OpenAPI Documentation
 *
 * OpenAPI spec version: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UpdateUserData {
    /**
    * In the sense of a legal name, not a username. The new name to assign to the user, if not provided, the current name will be used.
    */
    'name'?: string | null;
    /**
    * The id of the organization to update the user for.
    */
    'organizationId': string;
    /**
    * Either 0 (user), 1 (admin), or 2 (owner). If not provided, the current role will be used. The auth\'ed user must have a role greater than or equal to the role being assigned.
    */
    'role'?: number | null;
    /**
    * The id of the user to update, if not provided, the auth\'ed user will be updated. If provided, the auth\'ed user must be an admin (1) or owner (2) of the organization.
    */
    'userId'?: string | null;
    /**
    * The new username to assign to the user, if not provided, the current username will be used.
    */
    'username'?: string | null;
    /**
    * Determines if the user\'s email is visible to other users, if not provided, the current value will be used.
    */
    'visibleEmail'?: boolean | null;
    /**
    * The new website to assign to the user, if not provided, the current website will be used. Used for linking to the user\'s personal or company website.
    */
    'website'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "organizationId",
            "baseName": "organization_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string",
            "format": ""
        },
        {
            "name": "visibleEmail",
            "baseName": "visible_email",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "website",
            "baseName": "website",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateUserData.attributeTypeMap;
    }

    public constructor() {
    }
}

