/**
 * trieve-server
 * Trieve REST API OpenAPI Documentation
 *
 * OpenAPI spec version: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UpdateDatasetRequest {
    /**
    * The new client configuration of the dataset, can be arbitrary JSON. See docs.trieve.ai for more information. If not provided, the client configuration will not be updated.
    */
    'clientConfiguration'?: any | null;
    /**
    * The id of the dataset you want to update.
    */
    'datasetId': string;
    /**
    * The new name of the dataset. Must be unique within the organization. If not provided, the name will not be updated.
    */
    'datasetName'?: string | null;
    /**
    * The new server configuration of the dataset, can be arbitrary JSON. See docs.trieve.ai for more information. If not provided, the server configuration will not be updated.
    */
    'serverConfiguration'?: any | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "clientConfiguration",
            "baseName": "client_configuration",
            "type": "any",
            "format": ""
        },
        {
            "name": "datasetId",
            "baseName": "dataset_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "datasetName",
            "baseName": "dataset_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "serverConfiguration",
            "baseName": "server_configuration",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateDatasetRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

