/**
 * trieve-server
 * Trieve REST API OpenAPI Documentation
 *
 * OpenAPI spec version: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UploadFileResult {
    'fileMetadata': any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "fileMetadata",
            "baseName": "file_metadata",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UploadFileResult.attributeTypeMap;
    }

    public constructor() {
    }
}

