/**
 * trieve-server
 * Trieve REST API OpenAPI Documentation
 *
 * OpenAPI spec version: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UploadFileData {
    /**
    * Base64 encoded file. Convert + to -, / to _, and remove the ending = if present. This is the standard base64url encoding.
    */
    'base64File': string;
    /**
    * Create chunks is a boolean which determines whether or not to create chunks from the file. If false, you can manually chunk the file and send the chunks to the create_chunk endpoint with the file_id to associate chunks with the file. Meant mostly for advanced users.
    */
    'createChunks'?: boolean | null;
    /**
    * Description is an optional convience field so you do not have to remember what the file contains or is about. It will be included on the group resulting from the file which will hold its chunk.
    */
    'description'?: string | null;
    /**
    * MIME type of the file being uploaded.
    */
    'fileMimeType': string;
    /**
    * Name of the file being uploaded, including the extension.
    */
    'fileName': string;
    /**
    * Link to the file. This can also be any string. This can be used to filter when searching for the file\'s resulting chunks. The link value will not affect embedding creation.
    */
    'link'?: string | null;
    /**
    * Metadata is a JSON object which can be used to filter chunks. This is useful for when you want to filter chunks by arbitrary metadata. Unlike with tag filtering, there is a performance hit for filtering on metadata. Will be passed down to the file\'s chunks.
    */
    'metadata'?: any | null;
    /**
    * Tag set is a comma separated list of tags which will be passed down to the chunks made from the file. Tags are used to filter chunks when searching. HNSW indices are created for each tag such that there is no performance loss when filtering on them.
    */
    'tagSet'?: string | null;
    /**
    * Time stamp should be an ISO 8601 combined date and time without timezone. Time_stamp is used for time window filtering and recency-biasing search results. Will be passed down to the file\'s chunks.
    */
    'timeStamp'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "base64File",
            "baseName": "base64_file",
            "type": "string",
            "format": ""
        },
        {
            "name": "createChunks",
            "baseName": "create_chunks",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "fileMimeType",
            "baseName": "file_mime_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "fileName",
            "baseName": "file_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "link",
            "baseName": "link",
            "type": "string",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any",
            "format": ""
        },
        {
            "name": "tagSet",
            "baseName": "tag_set",
            "type": "string",
            "format": ""
        },
        {
            "name": "timeStamp",
            "baseName": "time_stamp",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UploadFileData.attributeTypeMap;
    }

    public constructor() {
    }
}

